# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'congrats_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_congrats_win(object):
    def setupUi(self, congrats_win):
        congrats_win.setObjectName("congrats_win")
        congrats_win.resize(474, 584)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(congrats_win.sizePolicy().hasHeightForWidth())
        congrats_win.setSizePolicy(sizePolicy)
        congrats_win.setMinimumSize(QtCore.QSize(474, 584))
        congrats_win.setMaximumSize(QtCore.QSize(474, 584))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        congrats_win.setWindowIcon(icon)
        congrats_win.setStyleSheet("")
        self.label_image = QtWidgets.QLabel(congrats_win)
        self.label_image.setGeometry(QtCore.QRect(0, 0, 474, 584))
        self.label_image.setMinimumSize(QtCore.QSize(474, 584))
        self.label_image.setStyleSheet("image:url(:/img/congrats.png)")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.label_winner = QtWidgets.QLabel(congrats_win)
        self.label_winner.setGeometry(QtCore.QRect(90, 240, 110, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_winner.sizePolicy().hasHeightForWidth())
        self.label_winner.setSizePolicy(sizePolicy)
        self.label_winner.setMinimumSize(QtCore.QSize(110, 40))
        self.label_winner.setMaximumSize(QtCore.QSize(110, 40))
        self.label_winner.setStyleSheet("font: 16pt \"SetoFont\";")
        self.label_winner.setText("")
        self.label_winner.setObjectName("label_winner")
        self.pushButton = QtWidgets.QPushButton(congrats_win)
        self.pushButton.setGeometry(QtCore.QRect(332, 540, 121, 28))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("font: 10pt \"SetoFont\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(congrats_win)
        QtCore.QMetaObject.connectSlotsByName(congrats_win)

    def retranslateUi(self, congrats_win):
        _translate = QtCore.QCoreApplication.translate
        congrats_win.setWindowTitle(_translate("congrats_win", "Congrats!"))
        self.pushButton.setText(_translate("congrats_win", "Thanks. Bye~"))
import background_rc
import game_rc
