# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help6.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help6_Dialog(object):
    def setupUi(self, Help6_Dialog):
        Help6_Dialog.setObjectName("Help6_Dialog")
        Help6_Dialog.resize(710, 840)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Help6_Dialog.sizePolicy().hasHeightForWidth())
        Help6_Dialog.setSizePolicy(sizePolicy)
        Help6_Dialog.setMinimumSize(QtCore.QSize(710, 840))
        Help6_Dialog.setMaximumSize(QtCore.QSize(710, 840))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Help6_Dialog.setWindowIcon(icon)
        Help6_Dialog.setStyleSheet("")
        self.label_6 = QtWidgets.QLabel(Help6_Dialog)
        self.label_6.setGeometry(QtCore.QRect(-40, 0, 790, 840))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(790, 840))
        self.label_6.setMaximumSize(QtCore.QSize(790, 840))
        self.label_6.setStyleSheet("image:url(:/img/help6.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Help6_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Help6_Dialog)

    def retranslateUi(self, Help6_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Help6_Dialog.setWindowTitle(_translate("Help6_Dialog", "PERUKE - How To Play (6 discs)"))
import background_rc
import game_rc
