# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import background
import game

class Ui_Help1_Dialog(object):
    def setupUi(self, Help1_Dialog):
        Help1_Dialog.setObjectName("Help1_Dialog")
        Help1_Dialog.resize(686, 770)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Help1_Dialog.sizePolicy().hasHeightForWidth())
        Help1_Dialog.setSizePolicy(sizePolicy)
        Help1_Dialog.setMinimumSize(QtCore.QSize(686, 770))
        Help1_Dialog.setMaximumSize(QtCore.QSize(686, 770))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Help1_Dialog.setWindowIcon(icon)
        Help1_Dialog.setStyleSheet("")
        self.label_1 = QtWidgets.QLabel(Help1_Dialog)
        self.label_1.setGeometry(QtCore.QRect(-10, 0, 711, 775))
        self.label_1.setMaximumSize(QtCore.QSize(774, 775))
        self.label_1.setStyleSheet("image:url(:/img/help1.png)")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")

        self.retranslateUi(Help1_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Help1_Dialog)

    def retranslateUi(self, Help1_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Help1_Dialog.setWindowTitle(_translate("Help1_Dialog", "PERUKE - How To Play (1 disc)"))

