# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import background


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1169, 848)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1169, 848))
        Form.setMaximumSize(QtCore.QSize(1169, 848))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.background_pic = QtWidgets.QLabel(Form)
        self.background_pic.setGeometry(QtCore.QRect(-30, -20, 1221, 881))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_pic.sizePolicy().hasHeightForWidth())
        self.background_pic.setSizePolicy(sizePolicy)
        self.background_pic.setMinimumSize(QtCore.QSize(1221, 881))
        self.background_pic.setMaximumSize(QtCore.QSize(1221, 881))
        self.background_pic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_pic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.background_pic.setAutoFillBackground(False)
        self.background_pic.setStyleSheet("image: url(:/newPrefix/background.png);")
        self.background_pic.setText("")
        self.background_pic.setObjectName("background_pic")
        self.start_pushButton = QtWidgets.QPushButton(Form)
        self.start_pushButton.setGeometry(QtCore.QRect(490, 730, 181, 61))
        self.start_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_pushButton.setMouseTracking(True)
        self.start_pushButton.setAutoFillBackground(False)
        self.start_pushButton.setStyleSheet("border-image: url(:/newPrefix/startbutton.png);")
        self.start_pushButton.setText("")
        self.start_pushButton.setIconSize(QtCore.QSize(200, 60))
        self.start_pushButton.setDefault(False)
        self.start_pushButton.setObjectName("start_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PERUKE"))
