# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

import background


class Ui_Signin_Window(object):
    def setupUi(self, Signin_Window):
        Signin_Window.setObjectName("Signin_Window")
        Signin_Window.resize(400, 580)
        Signin_Window.setMinimumSize(QtCore.QSize(400, 580))
        Signin_Window.setMaximumSize(QtCore.QSize(400, 580))
        Signin_Window.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Signin_Window.setWindowIcon(icon)
        Signin_Window.setToolTip("")
        Signin_Window.setWhatsThis("")
        Signin_Window.setStyleSheet("background-color: rgb(185, 198, 207);")
        self.signin_icon = QtWidgets.QLabel(Signin_Window)
        self.signin_icon.setGeometry(QtCore.QRect(110, 40, 171, 161))
        self.signin_icon.setStyleSheet("border-image: url(:/newPrefix/signin_icon.png);")
        self.signin_icon.setText("")
        self.signin_icon.setObjectName("signin_icon")
        self.signin_pushbutton = QtWidgets.QPushButton(Signin_Window)
        self.signin_pushbutton.setGeometry(QtCore.QRect(30, 460, 132, 61))
        self.signin_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin_pushbutton.setStyleSheet("border-image: url(:/newPrefix/signin_button.png);")
        self.signin_pushbutton.setText("")
        self.signin_pushbutton.setObjectName("signin_pushbutton")
        self.cancel_pushbutton = QtWidgets.QPushButton(Signin_Window)
        self.cancel_pushbutton.setGeometry(QtCore.QRect(240, 460, 130, 60))
        self.cancel_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_pushbutton.setStyleSheet("border-image: url(:/newPrefix/cancel_button.png);")
        self.cancel_pushbutton.setText("")
        self.cancel_pushbutton.setObjectName("cancel_pushbutton")
        self.gridLayoutWidget = QtWidgets.QWidget(Signin_Window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 240, 333, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.username_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.username_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.username_gridLayout.setObjectName("username_gridLayout")
        self.username_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_lineEdit.sizePolicy().hasHeightForWidth())
        self.username_lineEdit.setSizePolicy(sizePolicy)
        self.username_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"SetoFont\";\n"
"")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.username_gridLayout.addWidget(self.username_lineEdit, 1, 0, 1, 3)
        self.username_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.username_label.setStyleSheet("font: 15pt \"SetoFont\";")
        self.username_label.setObjectName("username_label")
        self.username_gridLayout.addWidget(self.username_label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.username_gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.username_gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Signin_Window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 340, 336, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.password_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.password_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.password_gridLayout.setObjectName("password_gridLayout")
        self.password_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineEdit.sizePolicy().hasHeightForWidth())
        self.password_lineEdit.setSizePolicy(sizePolicy)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"SetoFont\";\n"
"")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setMaxLength(20)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_gridLayout.addWidget(self.password_lineEdit, 1, 0, 1, 3)
        self.password_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.password_label.setStyleSheet("font: 15pt \"SetoFont\";")
        self.password_label.setObjectName("password_label")
        self.password_gridLayout.addWidget(self.password_label, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.password_gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.password_gridLayout.addItem(spacerItem3, 0, 0, 1, 1)

        self.retranslate_ui(Signin_Window)
        QtCore.QMetaObject.connectSlotsByName(Signin_Window)

        # self.signin_pushbutton.clicked.connect(self.check)
        self.cancel_pushbutton.clicked.connect(QtCore.QCoreApplication.instance().quit)   # 退出整个程序

    def retranslate_ui(self, Signin_Window):
        _translate = QtCore.QCoreApplication.translate
        Signin_Window.setWindowTitle(_translate("Signin_Window", "PERUKE - Sign in"))
        self.username_label.setText(_translate("Signin_Window", "User Name"))
        self.password_label.setText(_translate("Signin_Window", "Password"))

    # def check(self):
    #     username = self.username_lineEdit.text()
    #     password = self.password_lineEdit.text()
    #     if username != 'warwickIFP' or password != 'itisperuke':
    #         QtWidgets.QMessageBox.warning(None, "警告", "密码为空")
    #     else:
    #         self.close()



