# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets

# https://blog.csdn.net/weixin_45721776/article/details/113566192
import background

from login import Ui_Signin_Window


class Ui_Init_Window(object):
    def setupUi(self, Init_Window):
        Init_Window.setObjectName("Init_Window")
        Init_Window.resize(1163, 845)
        Init_Window.setMinimumSize(QtCore.QSize(1163, 845))
        Init_Window.setMaximumSize(QtCore.QSize(1163, 845))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Init_Window.setWindowIcon(icon)
        Init_Window.setWindowOpacity(5.0)
        Init_Window.setStyleSheet("background-color: rgb(158, 171, 228);")
        self.centralwidget = QtWidgets.QWidget(Init_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.background_pic = QtWidgets.QLabel(self.centralwidget)
        self.background_pic.setGeometry(QtCore.QRect(10, 0, 1141, 851))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_pic.sizePolicy().hasHeightForWidth())
        self.background_pic.setSizePolicy(sizePolicy)
        self.background_pic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_pic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.background_pic.setAutoFillBackground(False)
        self.background_pic.setStyleSheet("image: url(:/newPrefix/background.png);")
        self.background_pic.setText("")
        self.background_pic.setObjectName("background_pic")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(490, 740, 181, 61))
        self.start_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_pushButton.setMouseTracking(True)
        self.start_pushButton.setAutoFillBackground(False)
        self.start_pushButton.setStyleSheet("border-image: url(:/newPrefix/startbutton.png);")
        self.start_pushButton.setText("")
        self.start_pushButton.setIconSize(QtCore.QSize(200, 60))
        self.start_pushButton.setDefault(False)
        self.start_pushButton.setObjectName("start_pushButton")
        Init_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Init_Window)
        QtCore.QMetaObject.connectSlotsByName(Init_Window)

        self.start_pushButton.clicked.connect(self.popLoginWindow)   # 连接两个窗口

    def retranslateUi(self, Init_Window):
        _translate = QtCore.QCoreApplication.translate
        Init_Window.setWindowTitle(_translate("Init_Window", "PERUKE"))

    def popLoginWindow(self):   # 连接两个窗口
        self.form = QtWidgets.QWidget()
        self.ui = Ui_Signin_Window()
        self.ui.setupUi(self.form)
        self.form.show()


# https://blog.csdn.net/linmuquan1989/article/details/124141854
if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Init_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
