# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton, QDialog, QLabel

import background


class StartWindow(QWidget):
    def __init__(self):
        super(StartWindow, self).__init__()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1169, 848)

        self.form = Form  # 这一句是加的

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1169, 848))
        Form.setMaximumSize(QtCore.QSize(1169, 848))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.background_pic = QtWidgets.QLabel(Form)
        self.background_pic.setGeometry(QtCore.QRect(-30, -20, 1221, 881))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_pic.sizePolicy().hasHeightForWidth())
        self.background_pic.setSizePolicy(sizePolicy)
        self.background_pic.setMinimumSize(QtCore.QSize(1221, 881))
        self.background_pic.setMaximumSize(QtCore.QSize(1221, 881))
        self.background_pic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_pic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.background_pic.setAutoFillBackground(False)
        self.background_pic.setStyleSheet("image: url(:/newPrefix/background.png);")
        self.background_pic.setText("")
        self.background_pic.setObjectName("background_pic")
        self.start_pushButton = QtWidgets.QPushButton(Form)
        self.start_pushButton.setGeometry(QtCore.QRect(490, 730, 181, 61))
        self.start_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_pushButton.setMouseTracking(True)
        self.start_pushButton.setAutoFillBackground(False)
        self.start_pushButton.setStyleSheet("border-image: url(:/newPrefix/startbutton.png);")
        self.start_pushButton.setText("")
        self.start_pushButton.setIconSize(QtCore.QSize(200, 60))
        self.start_pushButton.setDefault(False)
        self.start_pushButton.setObjectName("start_pushButton")

        self.start_pushButton.clicked.connect(self.slot_start_pushbutton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PERUKE"))

# https://blog.csdn.net/qq_39914965/article/details/106028518?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0.pc_relevant_default&spm=1001.2101.3001.4242.1&utm_relevant_index=3
    def slot_start_pushbutton(self):
        self.form.hide()
        form1 = QDialog()
        first_dialog = LoginWindow()
        first_dialog.setupUi(form1)
        form1.show()
        form1.exec_()
        self.form.show()
        self.start_pushButton.hide()


class LoginWindow(QWidget):
    def setupUi(self, sign_window):
        sign_window.setObjectName("Signin_Window")
        sign_window.resize(400, 580)
        sign_window.setMinimumSize(QtCore.QSize(400, 580))
        sign_window.setMaximumSize(QtCore.QSize(400, 580))
        sign_window.setMouseTracking(True)

        self.form = sign_window   # 这一行是加的

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sign_window.setWindowIcon(icon)
        sign_window.setToolTip("")
        sign_window.setWhatsThis("")
        sign_window.setStyleSheet("background-color: rgb(185, 198, 207);")
        self.signin_icon = QtWidgets.QLabel(sign_window)
        self.signin_icon.setGeometry(QtCore.QRect(110, 40, 171, 161))
        self.signin_icon.setStyleSheet("border-image: url(:/newPrefix/signin_icon.png);")
        self.signin_icon.setText("")
        self.signin_icon.setObjectName("signin_icon")
        self.signin_pushbutton = QtWidgets.QPushButton(sign_window)
        self.signin_pushbutton.setGeometry(QtCore.QRect(30, 460, 132, 61))
        self.signin_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin_pushbutton.setStyleSheet("border-image: url(:/newPrefix/signin_button.png);")
        self.signin_pushbutton.setText("")
        self.signin_pushbutton.setObjectName("signin_pushbutton")
        self.cancel_pushbutton = QtWidgets.QPushButton(sign_window)
        self.cancel_pushbutton.setGeometry(QtCore.QRect(240, 460, 130, 60))
        self.cancel_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_pushbutton.setStyleSheet("border-image: url(:/newPrefix/cancel_button.png);")
        self.cancel_pushbutton.setText("")
        self.cancel_pushbutton.setObjectName("cancel_pushbutton")
        self.gridLayoutWidget = QtWidgets.QWidget(sign_window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 240, 333, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.username_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.username_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.username_gridLayout.setObjectName("username_gridLayout")
        self.username_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_lineEdit.sizePolicy().hasHeightForWidth())
        self.username_lineEdit.setSizePolicy(sizePolicy)
        self.username_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "font: 14pt \"SetoFont\";\n"
                                             "")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.username_gridLayout.addWidget(self.username_lineEdit, 1, 0, 1, 3)
        self.username_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.username_label.setStyleSheet("font: 15pt \"SetoFont\";")
        self.username_label.setObjectName("username_label")
        self.username_gridLayout.addWidget(self.username_label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.username_gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.username_gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(sign_window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 340, 336, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.password_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.password_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.password_gridLayout.setObjectName("password_gridLayout")
        self.password_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineEdit.sizePolicy().hasHeightForWidth())
        self.password_lineEdit.setSizePolicy(sizePolicy)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "font: 10pt \"SetoFont\";\n"
                                             "")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setMaxLength(20)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_gridLayout.addWidget(self.password_lineEdit, 1, 0, 1, 3)
        self.password_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.password_label.setStyleSheet("font: 15pt \"SetoFont\";")
        self.password_label.setObjectName("password_label")
        self.password_gridLayout.addWidget(self.password_label, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.password_gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.password_gridLayout.addItem(spacerItem3, 0, 0, 1, 1)

        self.retranslate_ui(sign_window)
        QtCore.QMetaObject.connectSlotsByName(sign_window)

        self.signin_pushbutton.clicked.connect(self.check)   # 这一行也是
        self.cancel_pushbutton.clicked.connect(QtCore.QCoreApplication.instance().quit)  # 退出整个程序

    def retranslate_ui(self, sign_window):
        _translate = QtCore.QCoreApplication.translate
        sign_window.setWindowTitle(_translate("Signin_Window", "PERUKE - Sign in"))
        self.username_label.setText(_translate("Signin_Window", "User Name"))
        self.password_label.setText(_translate("Signin_Window", "Password"))

    def check(self):
        username = self.username_lineEdit.text()
        password = self.password_lineEdit.text()
        if username != 'warwickIFP' or password != 'itisperuke':
            QtWidgets.QMessageBox.warning(None, "Wrong!", "Sorry, your information isn't correct\nPlease try again")
        else:
            self.form.close()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = StartWindow()
    Form = QWidget()
    w.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
